// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvZsoiiugwz7ipZYlti3LrBEXj6Z_4kY',
    appId: '1:138958715499:web:e8da2e2838a9c024fdcf2e',
    messagingSenderId: '138958715499',
    projectId: 'ineedcaffeine',
    authDomain: 'ineedcaffeine.firebaseapp.com',
    storageBucket: 'ineedcaffeine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2okGWufCda9nLLE-S5s-CW7sJz06JHw',
    appId: '1:138958715499:android:d3fbf83a5a8c931bfdcf2e',
    messagingSenderId: '138958715499',
    projectId: 'ineedcaffeine',
    storageBucket: 'ineedcaffeine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiPXck-xLznXPKiMOa6a36V9PmZRLDgyY',
    appId: '1:138958715499:ios:98915751833ce798fdcf2e',
    messagingSenderId: '138958715499',
    projectId: 'ineedcaffeine',
    storageBucket: 'ineedcaffeine.firebasestorage.app',
    iosBundleId: 'com.example.sdtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiPXck-xLznXPKiMOa6a36V9PmZRLDgyY',
    appId: '1:138958715499:ios:98915751833ce798fdcf2e',
    messagingSenderId: '138958715499',
    projectId: 'ineedcaffeine',
    storageBucket: 'ineedcaffeine.firebasestorage.app',
    iosBundleId: 'com.example.sdtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdvZsoiiugwz7ipZYlti3LrBEXj6Z_4kY',
    appId: '1:138958715499:web:bea6287091aa1c68fdcf2e',
    messagingSenderId: '138958715499',
    projectId: 'ineedcaffeine',
    authDomain: 'ineedcaffeine.firebaseapp.com',
    storageBucket: 'ineedcaffeine.firebasestorage.app',
  );
}